### ISSUE TITLE
component[1]指的是什么？

### ISSUE THREAD

**Issue by DsNull9797** [mocha-opts/umi-ft#1]
> "component[1].readyPost": "{{$deps[0] && $deps[1]}}",
                "component[1].phoneNumber": "{{$deps[0]}}",

你好，想请教一下这里的component[1].readyPost 和 component[1].phoneNumber 指的是什么？

**Comment by mocha-opts** [comment]
这一块本来想试试低代码的，这是Formily的json schema的配置，官网的例子：https://formilyjs.org/zh-CN/guide/scenes/login-register

**Comment by mocha-opts** [comment]
> > "component[1].readyPost": "{{$deps[0] && $deps[1]}}",
> > "component[1].phoneNumber": "{{$deps[0]}}",
> 
> 你好，想请教一下这里的component[1].readyPost 和 component[1].phoneNumber 指的是什么？
这一块本来想试试低代码的，这是Formily的json schema的配置，官网的例子：https://formilyjs.org/zh-CN/guide/scenes/login-register
